### ISSUE TITLE
crash converting QStringList to QSet

### ISSUE THREAD

**Issue by pieper** [commontk/AppLauncher#116]
Regression from https://github.com/commontk/AppLauncher/pull/113 led to crashes as described in https://github.com/Slicer/Slicer/issues/5078.

**Comment by muratmaga** [comment]
This still crashes for me

**Comment by lassoan** [comment]
How did you test it? You need a static build of Qt, which requires commercial license.

**Comment by jcfr** [comment]
> You need a static build of Qt, which requires commercial license.

Since the launcher is a standalone executable, we build Qt statically our-self and comply with the license requirements.

**Comment by jamesobutler** [comment]
Note the CTKAppLauncher git hash has not been updated https://github.com/Slicer/Slicer/blob/1a8a34060e491e659c7edd0dc2a7171ca12278ad/SuperBuild/External_CTKAppLauncherLib.cmake#L29

**Comment by jcfr** [comment]
To move forward:
* Update hash as suggested by @jamesobutler for using updated CTKAppLauncherLib
* Fix CI and generate a new AppLauncher release. See https://github.com/commontk/AppLauncher#maintainers-how-to-make-a-release-

**Comment by muratmaga** [comment]
> 
> 
> How did you test it? You need a static build of Qt, which requires commercial license.

I just downloaded the latest preview and installed dcm2niix and try to import one of @cpinter tiny patient datasets.
