### ISSUE TITLE
 ?" 

### ISSUE THREAD

**Issue by adamrankin** [commontk/AppLauncher#121]

**Comment by jcfr** [comment]
Closing. This issue was probably created by mistake.

**Comment by adamrankin** [comment]
Yes, sorry. The result of leaving my other issue tab open and leaving me son unsupervised for 15 seconds. *sigh*

**Comment by jcfr** [comment]
> The result of leaving my other issue tab open and leaving me son unsupervised for 15 seconds

Extreme programming at his best :)

**Comment by lassoan** [comment]
He is starting software development very early
