### ISSUE TITLE
Launcher should ignore arguments after an extra application argument

### ISSUE THREAD

**Issue by mwoehlke-kitware** [commontk/AppLauncher#52]
Consider Slicer, which has e.g. an extra application argument `--gdb`. If I want to read GDB's CLI help, I would run `/path/to/Slicer --gdb --help`. This works okay, _but_, the launcher _also_ reads the `--help` option and shows the help for `Slicer` as well.

Also, the launcher does not recognize `--` to ignore following options.

For extra applications, the launcher should ignore any arguments following the extra application argument, at least when preceded by `--`.

**Comment by jcfr** [comment]
Closing. The problem was addressed by the reference commit and issue.
