### ISSUE TITLE
Implement mechanism to keep track of original environment

### ISSUE THREAD

**Issue by jcfr** [commontk/AppLauncher#80]
As suggested by @lassoan , a robust way of keeping track of the original environment using the following approach:

We could save the original values of the modified/added/removed environment variables in other environment variables?

For example:

```
PATH=...new path with additional values...
PYTHONPATH=...modified by this applauncher...
LD_LIBRARY_PATH=...modified by this applauncher...
APPLAUNCHER_LEVEL=0
APPLAUNCHER_0_PATH=...original path before the applauncher modified it...
APPLAUNCHER_0_PYTHONPATH=...original path before the applauncher modified it...
APPLAUNCHER_0_SOME_DELETED_VAR=...stores value of a deleted env var DELETED_VAR...
APPLAUNCHER_0_SOME_ADDED_VAR=
```

To restore previous level's environment, you would just need to go through all the APPLAUNCHER_<LEVEL>_* variables and set them. Set to empty value deletes an env var, so this can be used for deleting added env vars as well.

APPLAUNCHER_LEVEL can be used for cleanly managing multiple levels off app launching (applauncher library running an application that uses applauncher). For example:

```
PATH=...new path with additional values...
PYTHONPATH=...modified by this applauncher...
LD_LIBRARY_PATH=...modified by this applauncher...
APPLAUNCHER_LEVEL=1
APPLAUNCHER_0_PATH=...original path before the applauncher modified it...
APPLAUNCHER_0_SOME_DELETED_VAR=...stores value of a deleted env var DELETED_VAR...
APPLAUNCHER_0_SOME_ADDED_VAR=
APPLAUNCHER_1_PATH=...original path before the applauncher modified it...
APPLAUNCHER_1_SOME_DELETED_VAR=...stores value of a deleted env var DELETED_VAR..
APPLAUNCHER_1_SOME_MORE_DELETED_VAR=...stores value of a deleted env var SOME_MORE_DELETED_VAR...
APPLAUNCHER_1_SOME_ADDED_VAR=
APPLAUNCHER_1_SOME_MORE_ADDED_VAR=
```

If a launcher did not modify any env vars then it would just increment APPLAUNCHER_LEVEL.

AppLauncher library could be responsible for creating environments from previous levels.

**Comment by jcfr** [comment]
Et voila, I have a use case for this :smile:  See https://github.com/Radiomics/SlicerRadiomics/issues/16

I am starting the implementation

**Comment by lassoan** [comment]
It happened sooner than I expected :)

**Comment by jcfr** [comment]
Fixed in #81 and #82

**Comment by ihnorton** [comment]
This reminds me of how CMake became CMake.

I can understand tracking the original Slicer invocation environment, but the idea of debugging multiple APPLAUNCHER_LEVELs is kind of scary. I don't know what @lassoan's use case is, but for https://github.com/Radiomics/SlicerRadiomics/issues/16 there is probably a simpler fix, which has been adopted in newer lsb releases: https://github.com/Radiomics/SlicerRadiomics/issues/16#issuecomment-333172070

**Comment by jcfr** [comment]
> the idea of debugging multiple APPLAUNCHER_LEVELs is kind of scary

Calling `environment(0)` given you the system env and that will be useful. We could add an alias method named `systemEnvironment()` to ctkAppLauncherLib

>  is probably a simpler fix, which has been adopted in newer lsb releases

Agree. The time being, just wanted to a solution that doesn't require asking developer to update their env manually.

When most of the distribution will have fix their system scripts, we can definitively remove the workaround.

**Comment by lassoan** [comment]
> I can understand tracking the original Slicer invocation environment, but the idea of debugging multiple APPLAUNCHER_LEVELs is kind of scary. I don't know what @lassoan's use case is

AppLauncher's modification of environment variables can have unpredictable side-effects. While there are always workarounds for neutralizing side-effects for a certain use case, the only way to avoid all side effects is to undo all changes that the AppLauncher has made.
